spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 570518782974-jdus84o00bp52n37raodfb01gv79usad.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email,openid

cloud:
  aws:
    credentials:
      accessKey: AKIA5EQM35EJGSBEMWF2
      secretKey: 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
      instanceProfile : true
    s3:
      bucket: miniprojectspring7
    region:
      static: ap-northeast-2
    stack:
      auto: false
